name: 'Deploy Terraform to AWS PROD'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-central-1"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format and Validation
      run: |
        cd ./prod/ 
        terraform init
        terraform validate

    - name: Terraform Plan
      run: cd ./prod/ && terraform plan

    - name: Terraform Apply
      run: cd ./prod/ && terraform apply -auto-approve
